### ISSUE TITLE
Class UfidReport is missing

### ISSUE THREAD

**Issue by tsufz** [bafg-bund/ntsworkflow#1]
Hi @ksjewell, 
During installation from source, the following error occurs. I checked the `report-class.R` and I cannot find the class or an alias.

```
Error: package or namespace load failed for ‘ntsworkflow’ in loadNamespace(package, lib.loc):
 in package ‘ntsworkflow’ classes UfidReport were specified for export but not defined
Error: loading failed
Execution halted
ERROR: loading failed
```

Yours,
Tobias

**Comment by ksjewell** [comment]
Thank you for finding this. After the new commit this error should be corrected.
